### ISSUE TITLE
Supply more output files in tutorial

### ISSUE THREAD

**Issue by zqbake** [joachimwolff/scHiCExplorer#11]
It would be helpful if more output files are available for users, especially outputs of different clustering methods.

**Comment by zqbake** [comment]
@joachimwolff Would you please share with us the output .txt file of each clustering method?

**Comment by joachimwolff** [comment]
Thank you for the reminder, I will take care of it.

**Comment by joachimwolff** [comment]
These are the requested files, computed on Nagano 2017 data with 1275 cells for which the cell labels were provided by Nagano. This is a different interaction matrix as mentioned in the tutorial: https://zenodo.org/record/4308298/files/nagano_1mb_cell_type.scool 

The dataset and the cell labels are part of a publication that is currently under review: https://zenodo.org/record/4308298#.X_XnWFNKiic

To compute the PCA, a small bug fix was required, see code in the develop branch. All used commands to compute the results have been computed with scHiCExplorer version 7 from the develop branch, please see commands.txt for the individual commands. 

Small side note: only the MinHash based computation creates reasonable clustering results. This can be seen by correlating the clusters with the labeled data provided by Nagano.

I hope this suits your expectations and please let me know if I can help you otherwise.

Best,

Joachim

[minhash.txt](https://github.com/joachimwolff/scHiCExplorer/files/5776949/minhash.txt)
[pca_cluster.txt](https://github.com/joachimwolff/scHiCExplorer/files/5776951/pca_cluster.txt)
[raw_cluster.txt](https://github.com/joachimwolff/scHiCExplorer/files/5776952/raw_cluster.txt)
[scikit_knn_cluster.txt](https://github.com/joachimwolff/scHiCExplorer/files/5776953/scikit_knn_cluster.txt)
[svl_results.txt](https://github.com/joachimwolff/scHiCExplorer/files/5776956/svl_results.txt)
[compartments_clustering.txt](https://github.com/joachimwolff/scHiCExplorer/files/5776957/compartments_clustering.txt)

[commands.txt](https://github.com/joachimwolff/scHiCExplorer/files/5776961/commands.txt)

**Comment by zqbake** [comment]
Thank you for your sharing.
